### ISSUE TITLE
Error when starting with VITE

### ISSUE THREAD

**Issue by IIPoliII** [lancache-ui/frontend#2]
Hello,

When I try to run the front end using the : `npm run dev --` command I have the following error :

```
failed to load config from /root/lancache-ui/frontend/vite.config.ts
error when starting dev server:
file:///root/lancache-ui/frontend/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@2.0.4_svelte@3.50.1_vite@3.1.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:2037
import { preprocessCSS, resolveConfig, transformWithEsbuild } from "vite";
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'vite' does not provide an export named 'preprocessCSS'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadConfigFromBundledFile (file:///root/lancache-ui/frontend/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63494:21)
    at async loadConfigFromFile (file:///root/lancache-ui/frontend/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63380:28)
    at async resolveConfig (file:///root/lancache-ui/frontend/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:62997:28)
    at async createServer (file:///root/lancache-ui/frontend/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:62063:20)
    at async CAC.<anonymous> (file:///root/lancache-ui/frontend/node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/cli.js:700:24)

```

I did everything right with the pnpm install too. This issue is on the latest Ubuntu 22.04 LTS.

I think something is wrong just with the deleraction of Vite. But I don't know JS very well.

**Comment by thomslor** [comment]
I found a solution, in package.json change the version of vite to 4.0.0 and svelte to 3.54.0

**Comment by IIPoliII** [comment]
> I found a solution, in package.json change the version of vite to 4.0.0 and svelte to 3.54.0

Thanks! I was able to start it but now I get 404 errors, it looks like it doesn't know where my lancache ui service is, but I don't know where I can set to point to it correctly, any idea by any chance?

**Comment by thomslor** [comment]
Found on the official Discord of LanCache.NET : 
* In the Frontend project in the file src/routes/dashbaord on line 7 change the line to read const serviceURL = 'http://localhost:3002' so that it looks for your instance of the backend service

If you are running the browser not on the server, put the IP of the server.
Still there will be 404 errors, as I understood that the project is still WIP.

**Comment by krisdahl** [comment]
I'm also getting 404 errors
